# -*- coding: utf-8 -*-
"""
/***************************************************************************
 gwr
                                 A QGIS plugin
 Geographically weighted regression
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-06-10
        git sha              : $Format:%H$
        copyright            : (C) 2018 by CS-Tao
        email                : whucstao@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import numpy as np
from qgis.utils import Qgis
from qgis.core import QgsVectorLayer
from PyQt5.QtCore import QSettings, QCoreApplication, QSize
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QAbstractItemView, QFileDialog, QTableWidgetItem

import os, sys
sys.path.append(os.path.abspath(os.path.dirname(__file__)))
import pygwr

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .gwr_dialog import gwrDialog
from .result_display_dialog import result_displayDialog
import os.path


class gwr:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'gwr_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = gwrDialog()
        self.result_display_dlg = result_displayDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&gwr')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'gwr')
        self.toolbar.setObjectName(u'gwr')

        # Data for gwr
        self.vectorLayers = []
        self.currentLayer = None
        self.data = []

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('gwr', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/gwr/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'gwr'),
            callback=self.run,
            parent=self.iface.mainWindow())

        formIcon = QIcon()
        formIcon.addFile(self.tr(":/plugins/gwr/icons/earth.png"))
        self.dlg.setWindowIcon(formIcon)
        openFileIcon = QIcon()
        openFileIcon.addFile(self.tr(":/plugins/gwr/icons/download.svg"))
        self.dlg.pushButton_OpenFile.setIcon(openFileIcon)
        self.dlg.pushButton_OpenFile.setIconSize(QSize(23, 23))
        refreshIcon = QIcon()
        refreshIcon.addFile(self.tr(":/plugins/gwr/icons/action_refresh.png"))
        self.dlg.pushButton_Refresh.setIcon(refreshIcon)
        self.dlg.pushButton_Refresh.setIconSize(QSize(23, 23))
        actionIcon = QIcon()
        actionIcon.addFile(self.tr(":/plugins/gwr/icons/mActionSetProjection.svg"))
        self.dlg.pushButton_Run.setIcon(actionIcon)
        cancelIcon = QIcon()
        cancelIcon.addFile(self.tr(":/plugins/gwr/icons/cancel.svg"))
        self.dlg.pushButton_Exit.setIcon(cancelIcon)
        
        self.dlg.comboBox_VectorLayers.currentIndexChanged.connect(self.selectLayerChanged)
        self.dlg.pushButton_OpenFile.clicked.connect(self.openFile)
        self.dlg.pushButton_Run.clicked.connect(self.runGwr)
        self.dlg.pushButton_Refresh.clicked.connect(self.refreshLayersList)
        self.dlg.listWidget_Independents.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.refreshLayersList()


    def selectLayerChanged(self, index):
        if len(self.vectorLayers) == 0 or index < 0 or index >= len(self.vectorLayers):
            return
        self.currentLayer = self.vectorLayers[index]
        self.iface.setActiveLayer(self.currentLayer)
        self.iface.zoomToActiveLayer()
        self.initFormByLayer(self.currentLayer)


    def openFile(self):
        # QMessageBox.question(self.dlg, 'test', 'test', QMessageBox.Ok)
        fileName, _ = QFileDialog.getOpenFileName(self.dlg, '打开文件', os.path.dirname(__file__), r'shp(*.shp)')
        if not fileName:
            return
        layer = self.iface.addVectorLayer(fileName, 'points', 'ogr')
        self.vectorLayers.append(layer)
        self.dlg.comboBox_VectorLayers.addItem(layer.name())
        self.dlg.comboBox_VectorLayers.setCurrentIndex(self.dlg.comboBox_VectorLayers.count() - 1)
        self.initFormByLayer(layer)


    def refreshLayersList(self):
        layers = self.iface.mapCanvas().layers()
        self.vectorLayers = []
        self.dlg.comboBox_VectorLayers.clear()
        for layer in layers:
            if isinstance(layer, QgsVectorLayer):
                self.vectorLayers.append(layer)
                self.dlg.comboBox_VectorLayers.addItem(layer.name())

    
    def initFormByLayer(self, layer):
        if not layer:
            self.showMsg("Error", "Layer failed to load!.", Qgis.Critical, 5)
            return
        self.dlg.comboBox_Dependent.clear()
        self.dlg.listWidget_Independents.clear()
        tempItem = QTableWidgetItem()
        col = 0
        for feild in layer.fields():
            tempItem.setText(self.tr(feild.displayName()))
            self.dlg.comboBox_Dependent.addItem(feild.displayName())
            self.dlg.listWidget_Independents.addItem(feild.displayName())
            row = 0
            for feature in layer.getFeatures():
                tempItem.setText(str(feature.attributes()[col]))
                row += 1
            col += 1
        self.data = []
        row = 0
        for feature in layer.getFeatures():
            rowData = []
            col = 0
            rowData.append(feature.geometry().asPoint().x())
            rowData.append(feature.geometry().asPoint().y())
            for feild in layer.fields():
                rowData.append(feature.attributes()[col])
            self.data.append(rowData)


    def runGwr(self):
        dataNp = np.array(self.data, dtype=np.float64)
        xSelected = self.dlg.listWidget_Independents.selectedItems()
        xIndexes = []
        for xTemp in xSelected:
            xIndexes.append(self.dlg.listWidget_Independents.row(xTemp) + 2)
        locations = dataNp[:, [0, 1]]
        dependent = dataNp[:, self.dlg.comboBox_Dependent.currentIndex() + 2]
        independent = dataNp[:, xIndexes]

        # Create gwr model
        # if self.dlg.radioButton_Gaussian.isChecked():
        #     model = pygwr.GWR(targets=dependent, samples=independent, locations=locations, kernel=pygwr.Gaussian())
        # else:
        #     model = pygwr.GWR(targets=dependent, samples=independent, locations=locations, family='poisson')
        model = pygwr.GWR(targets=dependent, samples=independent, locations=locations, family='poisson')
        globalfit = model.global_regression()
        gobal_result = str(globalfit.summary())
        # QMessageBox.question(self.dlg, 'test', str(globalfit.summary()), QMessageBox.Ok)
        bwmin, bwmax, bwstep = 5000, 20000, 1000
        opt_bw, opt_aicc = None, np.inf
        for bw in range(bwmin, bwmax+bwstep, bwstep):
            aicc = model.aicc(bw)
            if aicc['aicc'] < opt_aicc:
                opt_bw, opt_aicc = bw, aicc['aicc']

        # Estimate the GWR model at all data points
        gwr_result = model.estimate_at_target_locations(bandwidth=opt_bw)

        tableHeader, tableData = gwr_result.getTableInfo()
        
        self.result_display_dlg.showResult(self.currentLayer, gobal_result, tableHeader, tableData)


    def showMsg(self, title, message, level=Qgis.Info, duration=5):
        self.iface.messageBar().pushMessage(title, message, level, duration)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&gwr'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar


    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
